const nodemailer = require('nodemailer');
const { logger } = require('../utils/logger');

const {
  RESEND_API_KEY,
  SMTP_HOST,
  SMTP_PORT,
  SMTP_USER,
  SMTP_PASS,
  SMTP_SECURE,
  SMTP_CONNECTION_TIMEOUT_MS,
  SMTP_GREETING_TIMEOUT_MS,
  SMTP_SOCKET_TIMEOUT_MS,
  REPORT_FROM_EMAIL,
  NODE_ENV,
} = process.env;

const toPositiveInt = (value, fallback) => {
  const n = parseInt(value, 10);
  return Number.isFinite(n) && n > 0 ? n : fallback;
};

const MAIL_TIMEOUTS = {
  connectionTimeout: toPositiveInt(SMTP_CONNECTION_TIMEOUT_MS, 10000),
  greetingTimeout: toPositiveInt(SMTP_GREETING_TIMEOUT_MS, 10000),
  socketTimeout: toPositiveInt(SMTP_SOCKET_TIMEOUT_MS, 15000),
};

function createTransport() {
  if (RESEND_API_KEY) {
    return nodemailer.createTransport({
      host: 'smtp.resend.com',
      port: 465,
      secure: true,
      auth: { user: 'resend', pass: RESEND_API_KEY },
      ...MAIL_TIMEOUTS,
    });
  }

  if (SMTP_HOST) {
    return nodemailer.createTransport({
      host: SMTP_HOST,
      port: parseInt(SMTP_PORT, 10) || 587,
      secure: SMTP_SECURE === 'true',
      auth: { user: SMTP_USER, pass: SMTP_PASS },
      ...MAIL_TIMEOUTS,
    });
  }

  return null;
}

const transporter = createTransport();

const fromAddress = REPORT_FROM_EMAIL || 'reports@ecopulse.local';

function isConfigured() {
  return transporter !== null;
}

function getProvider() {
  if (RESEND_API_KEY) return 'resend';
  if (SMTP_HOST) return 'smtp';
  return 'none';
}

const { PERIOD_MAP } = require('../utils/periodHelpers');

const escapeHtml = (input) =>
  String(input)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');

const PERIOD_SUBJECT_MAP = {
  '7d': 'Last 7 days',
  '14d': 'Last 14 days',
  '30d': 'Last 30 days',
};

function buildReportEmailSubject(period) {
  const label = PERIOD_SUBJECT_MAP[period] || PERIOD_MAP[period]?.label || period;
  return `EcoPulse Energy Report \u2014 ${label}`;
}

function buildReportEmailBody({ userName, period }) {
  const label = escapeHtml(PERIOD_SUBJECT_MAP[period] || PERIOD_MAP[period]?.label || period);
  const safeName = userName ? escapeHtml(userName) : '';
  return `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2e7d32;">EcoPulse Energy Report</h2>
      <p>Hello${safeName ? ' ' + safeName : ''},</p>
      <p>Please find your detailed energy report for <strong>${label}</strong> attached to this email as a PDF.</p>
      <p>The report covers your personal energy data, grid-wide statistics, and trading activity.</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="font-size: 12px; color: #888;">
        This report was generated by EcoPulse.
        ${process.env.NODE_ENV !== 'production' ? ' Data is based on simulated demo values.' : ''}
      </p>
    </div>
  `.trim();
}

async function sendReport({ to, subject, html, pdfBuffer, filename }) {
  if (!transporter) {
    throw new Error('Email transport not configured');
  }

  const result = await transporter.sendMail({
    from: fromAddress,
    to,
    subject,
    html,
    attachments: [
      {
        filename: filename || 'ecopulse-report.pdf',
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  });

  return result;
}

async function sendEmail({ to, subject, html }) {
  if (!transporter) {
    throw new Error('Email transport not configured');
  }
  return transporter.sendMail({ from: fromAddress, to, subject, html });
}

/**
 * Send a transactional email with bounded retry + structured logging.
 *
 * SMTP failures (auth rejected, transient 4xx, timeouts) were previously
 * swallowed by a bare console.warn in the caller, making them invisible to
 * operators. This helper logs every attempt (with the SMTP code/response,
 * e.g. EAUTH / 535) so delivery failures are diagnosable, and retries
 * transient errors with exponential backoff. A permanent failure is logged
 * at error level.
 */
async function sendEmailWithRetry(payload, { attempts = 3, baseDelayMs = 1500 } = {}) {
  let lastErr;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const res = await sendEmail(payload);
      logger.info('transactional email sent', {
        to: payload.to,
        subject: payload.subject,
        attempt,
        messageId: res?.messageId,
      });
      return res;
    } catch (err) {
      lastErr = err;
      logger.warn('transactional email send failed', {
        to: payload.to,
        subject: payload.subject,
        attempt,
        attempts,
        err,
        code: err?.code,
        responseCode: err?.responseCode,
        response: typeof err?.response === 'string' ? err.response.slice(0, 200) : undefined,
      });
      if (attempt < attempts) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
    }
  }
  logger.error('transactional email permanently failed', {
    to: payload.to,
    subject: payload.subject,
    err: lastErr,
  });
  throw lastErr;
}

function buildVerificationEmailBody({ userName, verificationUrl }) {
  const safeName = userName ? escapeHtml(userName) : 'there';
  const safeUrl = escapeHtml(verificationUrl);
  return `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2e7d32;">Verify Your EcoPulse Account</h2>
      <p>Hello ${safeName},</p>
      <p>Please verify your email address by clicking the button below:</p>
      <p style="margin: 24px 0;">
        <a href="${safeUrl}" style="background: #2e7d32; color: #fff; padding: 12px 28px; text-decoration: none; border-radius: 6px; display: inline-block;">Verify Email</a>
      </p>
      <p style="font-size: 13px; color: #666;">Or copy this link into your browser:<br /><a href="${safeUrl}">${safeUrl}</a></p>
      <p style="font-size: 13px; color: #666;">This link expires in 24 hours. If you did not create an account, you can safely ignore this email.</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="font-size: 12px; color: #888;">This email was sent by EcoPulse.</p>
    </div>
  `.trim();
}

function buildVerificationUrl(token) {
  const base = process.env.FRONTEND_URL || process.env.CORS_ORIGIN || 'https://app.ecopulse.local';
  return `${base.replace(/\/+$/, '')}/verify-email?token=${token}`;
}

function canSendEmail(user) {
  if (!user || !user.email) {
    return { allowed: false, reason: 'No email address on file.' };
  }
  if (user.preferences && user.preferences.emailNotifications === false) {
    return { allowed: false, reason: 'Email notifications are disabled in your preferences.' };
  }
  return { allowed: true };
}

module.exports = { transporter, fromAddress, isConfigured, getProvider, sendReport, sendEmail, sendEmailWithRetry, buildReportEmailSubject, buildReportEmailBody, buildVerificationEmailBody, buildVerificationUrl, canSendEmail };
