const nodemailer = require('nodemailer');

const {
  RESEND_API_KEY,
  SMTP_HOST,
  SMTP_PORT,
  SMTP_USER,
  SMTP_PASS,
  SMTP_SECURE,
  REPORT_FROM_EMAIL,
  NODE_ENV,
} = process.env;

function createTransport() {
  if (RESEND_API_KEY) {
    return nodemailer.createTransport({
      host: 'smtp.resend.com',
      port: 465,
      secure: true,
      auth: { user: 'resend', pass: RESEND_API_KEY },
    });
  }

  if (SMTP_HOST) {
    return nodemailer.createTransport({
      host: SMTP_HOST,
      port: parseInt(SMTP_PORT, 10) || 587,
      secure: SMTP_SECURE === 'true',
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });
  }

  return null;
}

const transporter = createTransport();

const fromAddress = REPORT_FROM_EMAIL || 'reports@ecopulse.local';

function isConfigured() {
  return transporter !== null;
}

function getProvider() {
  if (RESEND_API_KEY) return 'resend';
  if (SMTP_HOST) return 'smtp';
  return 'none';
}

const { PERIOD_MAP } = require('../utils/periodHelpers');

const PERIOD_SUBJECT_MAP = {
  '7d': 'Last 7 days',
  '14d': 'Last 14 days',
  '30d': 'Last 30 days',
};

function buildReportEmailSubject(period) {
  const label = PERIOD_SUBJECT_MAP[period] || PERIOD_MAP[period]?.label || period;
  return `EcoPulse Energy Report \u2014 ${label}`;
}

function buildReportEmailBody({ userName, period }) {
  const label = PERIOD_SUBJECT_MAP[period] || PERIOD_MAP[period]?.label || period;
  return `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2e7d32;">EcoPulse Energy Report</h2>
      <p>Hello${userName ? ' ' + userName : ''},</p>
      <p>Please find your detailed energy report for <strong>${label}</strong> attached to this email as a PDF.</p>
      <p>The report covers your personal energy data, grid-wide statistics, and trading activity.</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="font-size: 12px; color: #888;">
        This report was generated by EcoPulse.
        ${process.env.NODE_ENV !== 'production' ? ' Data is based on simulated demo values.' : ''}
      </p>
    </div>
  `.trim();
}

async function sendReport({ to, subject, html, pdfBuffer, filename }) {
  if (!transporter) {
    throw new Error('Email transport not configured');
  }

  const result = await transporter.sendMail({
    from: fromAddress,
    to,
    subject,
    html,
    attachments: [
      {
        filename: filename || 'ecopulse-report.pdf',
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  });

  return result;
}

function canSendEmail(user) {
  if (!user || !user.email) {
    return { allowed: false, reason: 'No email address on file.' };
  }
  if (user.preferences && user.preferences.emailNotifications === false) {
    return { allowed: false, reason: 'Email notifications are disabled in your preferences.' };
  }
  return { allowed: true };
}

module.exports = { transporter, fromAddress, isConfigured, getProvider, sendReport, buildReportEmailSubject, buildReportEmailBody, canSendEmail };
