// Fallback (human-readable) ABI for CarbonCreditBridge (Module 5.3.3).
// The compiled artifact is preferred at runtime via blockchainService.loadArtifactAbi.
module.exports = [
  'function lock(uint256 amount, uint256 targetChainId, address recipient) public',
  'function returnToSource(uint256 amount, uint256 sourceChainId) public',
  'function mintFor(address recipient, uint256 amount, uint256 sourceChainId, uint256 nonce) public',
  'function releaseBack(address recipient, uint256 amount, uint256 sourceChainId, uint256 nonce) public',
  'function pause() public',
  'function unpause() public',
  'function setSupportedChain(uint256 chainId, bool enabled) public',
  'function grantRelayer(address account) public',
  'function revokeRelayer(address account) public',
  'function token() view returns (address)',
  'function maxPerTx() view returns (uint256)',
  'function dailyCap() view returns (uint256)',
  'function nextLockId() view returns (uint256)',
  'function nextReturnId() view returns (uint256)',
  'function totalLockedIn() view returns (uint256)',
  'function supportedChains(uint256) view returns (bool)',
  'function processedNonces(bytes32) view returns (bool)',
  'function dailyLocked(uint256) view returns (uint256)',
  'function getBridgeBalance() view returns (uint256)',
  'function dailyRemaining() view returns (uint256)',
  'function RELAYER_ROLE() view returns (bytes32)',
  'event Locked(uint256 indexed lockId, address indexed sender, address indexed recipient, uint256 amount, uint256 indexed targetChainId)',
  'event Minted(uint256 indexed nonce, address indexed recipient, uint256 amount, uint256 indexed sourceChainId, address relayer)',
  'event ReturnedToSource(uint256 indexed returnId, address indexed sender, uint256 amount, uint256 indexed sourceChainId)',
  'event Released(uint256 indexed returnId, address indexed recipient, uint256 amount, uint256 indexed sourceChainId, address relayer)',
  'event SupportedChainSet(uint256 indexed chainId, bool enabled)',
  'event DailyCapConsumed(uint256 indexed dayBucket, uint256 consumed)',
];
